version: '3.8'

services:

  spring_main_service:
    container_name: spring_main_service
    depends_on:
      - postgres
      - spring_logger_service
    build:
      context: .
      dockerfile: server/Dockerfile
    networks:
      - postgres
      - kafka-net
    ports:
      - "8080:8080"

  spring_logger_service:
    container_name: spring_logger_service
    depends_on:
      - postgres
      - kafka
    build:
      context: .
      dockerfile: logger/Dockerfile
    networks:
      - postgres
      - kafka-net

  postgres:
    image: 'postgres:latest'
    container_name: postgres
    environment:
      - 'POSTGRES_DB=messenger'
      - 'POSTGRES_PASSWORD=1896748249'
      - 'POSTGRES_USER=xpm'
    networks:
      - postgres
    ports:
      - '5432:5432'
    volumes:
      - ./.database:/var/lib/postgresql

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    networks:
      - kafka-net

  kafka:
    depends_on:
      - zookeeper
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092, OUTSIDE://localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    networks:
      - kafka-net

networks:
  kafka-net:
    driver: bridge
  postgres:
    driver: bridge