spring:

  sql:
    init:
      mode: always

  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: logger
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: '*'
    listener:
      concurrency: 3
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  
  application:
    name: logger

  datasource:
    url: jdbc:postgresql://postgres:5432/messenger
    username: xpm
    password: 1896748249

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: logger
#    show-sql: true

server:
  port: 8081
